// const test = [
// 	{
// 		id: 22672013,
// 		lessonId: 275317,
// 		lessonNumber: 402401,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 900,
// 		endTime: 930,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090348_4024',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22676693,
// 		lessonId: 275317,
// 		lessonNumber: 402401,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 930,
// 		endTime: 1000,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090348_4024',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22672193,
// 		lessonId: 275312,
// 		lessonNumber: 402400,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 900,
// 		endTime: 930,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090144_4024',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22676828,
// 		lessonId: 275312,
// 		lessonNumber: 402400,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 930,
// 		endTime: 1000,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090144_4024',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22584158,
// 		lessonId: 275409,
// 		lessonNumber: 403500,
// 		lessonCode: 'LESSON',
// 		lessonText: 'basis',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230329,
// 		startTime: 1030,
// 		endTime: 1100,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092204_4035',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22257458,
// 		lessonId: 275409,
// 		lessonNumber: 403500,
// 		lessonCode: 'LESSON',
// 		lessonText: 'basis',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230329,
// 		startTime: 1100,
// 		endTime: 1130,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092204_4035',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22257463,
// 		lessonId: 275409,
// 		lessonNumber: 403500,
// 		lessonCode: 'LESSON',
// 		lessonText: 'basis',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230329,
// 		startTime: 1130,
// 		endTime: 1200,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092204_4035',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22667818,
// 		lessonId: 275414,
// 		lessonNumber: 403600,
// 		lessonCode: 'LESSON',
// 		lessonText: 'Cloudcomputing',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230329,
// 		startTime: 1230,
// 		endTime: 1300,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092206_4036',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22667823,
// 		lessonId: 275414,
// 		lessonNumber: 403600,
// 		lessonCode: 'LESSON',
// 		lessonText: 'Cloudcomputing',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230329,
// 		startTime: 1300,
// 		endTime: 1330,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092206_4036',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22667828,
// 		lessonId: 275414,
// 		lessonNumber: 403600,
// 		lessonCode: 'LESSON',
// 		lessonText: 'Cloudcomputing',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230329,
// 		startTime: 1330,
// 		endTime: 1400,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092206_4036',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22257733,
// 		lessonId: 275419,
// 		lessonNumber: 403700,
// 		lessonCode: 'LESSON',
// 		lessonText: 'Cloudcomputing',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230330,
// 		startTime: 900,
// 		endTime: 930,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092207_4037',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22257738,
// 		lessonId: 275419,
// 		lessonNumber: 403700,
// 		lessonCode: 'LESSON',
// 		lessonText: 'Cloudcomputing',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230330,
// 		startTime: 930,
// 		endTime: 1000,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092207_4037',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22593325,
// 		lessonId: 275419,
// 		lessonNumber: 403700,
// 		lessonCode: 'LESSON',
// 		lessonText: 'Cloudcomputing',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230330,
// 		startTime: 1000,
// 		endTime: 1030,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092207_4037',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22257863,
// 		lessonId: 275332,
// 		lessonNumber: 403100,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230331,
// 		startTime: 900,
// 		endTime: 930,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090157_4031',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22257868,
// 		lessonId: 275332,
// 		lessonNumber: 403100,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230331,
// 		startTime: 930,
// 		endTime: 1000,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090157_4031',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22257873,
// 		lessonId: 275332,
// 		lessonNumber: 403100,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230331,
// 		startTime: 1000,
// 		endTime: 1030,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090157_4031',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22672578,
// 		lessonId: 283175,
// 		lessonNumber: 403401,
// 		lessonCode: 'LESSON',
// 		lessonText: '+Devices(hardware)',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230331,
// 		startTime: 1030,
// 		endTime: 1100,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230202144433_4034',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22672583,
// 		lessonId: 283175,
// 		lessonNumber: 403401,
// 		lessonCode: 'LESSON',
// 		lessonText: '+Devices(hardware)',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230331,
// 		startTime: 1100,
// 		endTime: 1130,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230202144433_4034',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22672588,
// 		lessonId: 283175,
// 		lessonNumber: 403401,
// 		lessonCode: 'LESSON',
// 		lessonText: '+Devices(hardware)',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230331,
// 		startTime: 1130,
// 		endTime: 1200,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230202144433_4034',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22672823,
// 		lessonId: 275337,
// 		lessonNumber: 402500,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 1000,
// 		endTime: 1030,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090145_4025',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22677443,
// 		lessonId: 275337,
// 		lessonNumber: 402500,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 1030,
// 		endTime: 1100,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090145_4025',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22258108,
// 		lessonId: 275429,
// 		lessonNumber: 403800,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230330,
// 		startTime: 1030,
// 		endTime: 1100,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092209_4038',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22258113,
// 		lessonId: 275429,
// 		lessonNumber: 403800,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230330,
// 		startTime: 1100,
// 		endTime: 1130,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092209_4038',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22594735,
// 		lessonId: 275429,
// 		lessonNumber: 403800,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230330,
// 		startTime: 1130,
// 		endTime: 1200,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092209_4038',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22668048,
// 		lessonId: 275434,
// 		lessonNumber: 403900,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 1300,
// 		endTime: 1330,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092210_4039',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22668053,
// 		lessonId: 275434,
// 		lessonNumber: 403900,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 1330,
// 		endTime: 1400,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092210_4039',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22677658,
// 		lessonId: 275434,
// 		lessonNumber: 403900,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 1400,
// 		endTime: 1430,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092210_4039',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22673268,
// 		lessonId: 283185,
// 		lessonNumber: 537300,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1100,
// 		endTime: 1130,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230202142711_5373',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22673273,
// 		lessonId: 283185,
// 		lessonNumber: 537300,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1130,
// 		endTime: 1200,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230202142711_5373',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22673278,
// 		lessonId: 283185,
// 		lessonNumber: 537300,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1200,
// 		endTime: 1230,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230202142711_5373',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22673283,
// 		lessonId: 283185,
// 		lessonNumber: 537300,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1230,
// 		endTime: 1300,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230202142711_5373',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22677823,
// 		lessonId: 283318,
// 		lessonNumber: 538500,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 1500,
// 		endTime: 1530,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230203133239_5385',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22677828,
// 		lessonId: 283318,
// 		lessonNumber: 538500,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 1530,
// 		endTime: 1600,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230203133239_5385',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22258508,
// 		lessonId: 275444,
// 		lessonNumber: 403400,
// 		lessonCode: 'LESSON',
// 		lessonText: '+Devices(hardware)',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230331,
// 		startTime: 1030,
// 		endTime: 1100,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092007_4034',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22258513,
// 		lessonId: 275444,
// 		lessonNumber: 403400,
// 		lessonCode: 'LESSON',
// 		lessonText: '+Devices(hardware)',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230331,
// 		startTime: 1100,
// 		endTime: 1130,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092007_4034',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22258518,
// 		lessonId: 275444,
// 		lessonNumber: 403400,
// 		lessonCode: 'LESSON',
// 		lessonText: '+Devices(hardware)',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230331,
// 		startTime: 1130,
// 		endTime: 1200,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092007_4034',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22673553,
// 		lessonId: 283195,
// 		lessonNumber: 403101,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230331,
// 		startTime: 900,
// 		endTime: 930,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230202144342_4031',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22673558,
// 		lessonId: 283195,
// 		lessonNumber: 403101,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230331,
// 		startTime: 930,
// 		endTime: 1000,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230202144342_4031',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22673563,
// 		lessonId: 283195,
// 		lessonNumber: 403101,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230331,
// 		startTime: 1000,
// 		endTime: 1030,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230202144342_4031',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22258378,
// 		lessonId: 275439,
// 		lessonNumber: 403300,
// 		lessonCode: 'LESSON',
// 		lessonText: '+Devices(hardware)',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 1100,
// 		endTime: 1130,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092004_4033',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22258383,
// 		lessonId: 275439,
// 		lessonNumber: 403300,
// 		lessonCode: 'LESSON',
// 		lessonText: '+Devices(hardware)',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 1130,
// 		endTime: 1200,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092004_4033',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22677883,
// 		lessonId: 275439,
// 		lessonNumber: 403300,
// 		lessonCode: 'LESSON',
// 		lessonText: '+Devices(hardware)',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230327,
// 		startTime: 1200,
// 		endTime: 1230,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205092004_4033',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22628665,
// 		lessonId: 275347,
// 		lessonNumber: 402800,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230330,
// 		startTime: 1230,
// 		endTime: 1300,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090152_4028',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22258793,
// 		lessonId: 275347,
// 		lessonNumber: 402800,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230330,
// 		startTime: 1300,
// 		endTime: 1330,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090152_4028',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22668148,
// 		lessonId: 275352,
// 		lessonNumber: 402900,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230329,
// 		startTime: 1400,
// 		endTime: 1430,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090153_4029',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22668153,
// 		lessonId: 275352,
// 		lessonNumber: 402900,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230329,
// 		startTime: 1430,
// 		endTime: 1500,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20221205090153_4029',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701260,
// 		lessonId: 284249,
// 		lessonNumber: 557800,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1330,
// 		endTime: 1400,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155130_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701265,
// 		lessonId: 284249,
// 		lessonNumber: 557800,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1400,
// 		endTime: 1430,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155130_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701270,
// 		lessonId: 284249,
// 		lessonNumber: 557800,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1430,
// 		endTime: 1500,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155130_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701275,
// 		lessonId: 284249,
// 		lessonNumber: 557800,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1500,
// 		endTime: 1530,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155130_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701280,
// 		lessonId: 284249,
// 		lessonNumber: 557800,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1530,
// 		endTime: 1600,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155130_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701285,
// 		lessonId: 284249,
// 		lessonNumber: 557800,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1600,
// 		endTime: 1630,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155130_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701290,
// 		lessonId: 284249,
// 		lessonNumber: 557800,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1630,
// 		endTime: 1700,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155130_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701505,
// 		lessonId: 284254,
// 		lessonNumber: 557801,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1330,
// 		endTime: 1400,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155208_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701510,
// 		lessonId: 284254,
// 		lessonNumber: 557801,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1400,
// 		endTime: 1430,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155208_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701515,
// 		lessonId: 284254,
// 		lessonNumber: 557801,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1430,
// 		endTime: 1500,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155208_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701520,
// 		lessonId: 284254,
// 		lessonNumber: 557801,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1500,
// 		endTime: 1530,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155208_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701525,
// 		lessonId: 284254,
// 		lessonNumber: 557801,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1530,
// 		endTime: 1600,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155208_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701530,
// 		lessonId: 284254,
// 		lessonNumber: 557801,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1600,
// 		endTime: 1630,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155208_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// 	{
// 		id: 22701535,
// 		lessonId: 284254,
// 		lessonNumber: 557801,
// 		lessonCode: 'LESSON',
// 		lessonText: '',
// 		periodText: '',
// 		hasPeriodText: false,
// 		periodInfo: '',
// 		periodAttachments: [],
// 		substText: '',
// 		date: 20230328,
// 		startTime: 1630,
// 		endTime: 1700,
// 		elements: [[Object], [Object], [Object], [Object], [Object]],
// 		studentGroup: 'SG20230216155208_5578',
// 		hasInfo: false,
// 		code: 0,
// 		cellState: 'STANDARD',
// 		priority: 5,
// 		is: { standard: true, event: false },
// 		roomCapacity: 0,
// 		studentCount: 0,
// 	},
// ];

const test = [
	{
		id: 22672013,
		lessonId: 275317,
		lessonNumber: 402401,
		lessonCode: 'LESSON',
		lessonText: '',
		periodText: '',
		hasPeriodText: false,
		periodInfo: '',
		periodAttachments: [],
		substText: '',
		date: 20230327,
		startTime: 900,
		endTime: 930,
		elements: [[Array], [Array], [Array], [Array], [Array]],
		studentGroup: 'SG20221205090348_4024',
		hasInfo: false,
		code: 0,
		cellState: 'STANDARD',
		priority: 5,
		is: { standard: true, event: false },
		roomCapacity: 0,
		studentCount: 0,
	},
	{
		id: 22676693,
		lessonId: 275317,
		lessonNumber: 402401,
		lessonCode: 'LESSON',
		lessonText: '',
		periodText: '',
		hasPeriodText: false,
		periodInfo: '',
		periodAttachments: [],
		substText: '',
		date: 20230327,
		startTime: 930,
		endTime: 1000,
		elements: [[Array], [Array], [Array], [Array], [Array]],
		studentGroup: 'SG20221205090348_4024',
		hasInfo: false,
		code: 0,
		cellState: 'STANDARD',
		priority: 5,
		is: { standard: true, event: false },
		roomCapacity: 0,
		studentCount: 0,
	},
	{
		id: 22677883,
		lessonId: 275439,
		lessonNumber: 403300,
		lessonCode: 'LESSON',
		lessonText: '+Devices(hardware)',
		periodText: '',
		hasPeriodText: false,
		periodInfo: '',
		periodAttachments: [],
		substText: '',
		date: 20230327,
		startTime: 1200,
		endTime: 1230,
		elements: [[Array], [Array], [Array], [Array], [Array]],
		studentGroup: 'SG20221205092004_4033',
		hasInfo: false,
		code: 0,
		cellState: 'STANDARD',
		priority: 5,
		is: { standard: true, event: false },
		roomCapacity: 0,
		studentCount: 0,
	},
	{
		id: 22258508,
		lessonId: 275444,
		lessonNumber: 403400,
		lessonCode: 'LESSON',
		lessonText: '+Devices(hardware)',
		periodText: '',
		hasPeriodText: false,
		periodInfo: '',
		periodAttachments: [],
		substText: '',
		date: 20230331,
		startTime: 1030,
		endTime: 1100,
		elements: [[Object], [Object], [Object], [Object], [Object]],
		studentGroup: 'SG20221205092007_4034',
		hasInfo: false,
		code: 0,
		cellState: 'STANDARD',
		priority: 5,
		is: { standard: true, event: false },
		roomCapacity: 0,
		studentCount: 0,
	},
	{
		id: 22258513,
		lessonId: 275444,
		lessonNumber: 403400,
		lessonCode: 'LESSON',
		lessonText: '+Devices(hardware)',
		periodText: '',
		hasPeriodText: false,
		periodInfo: '',
		periodAttachments: [],
		substText: '',
		date: 20230331,
		startTime: 1100,
		endTime: 1130,
		elements: [[Object], [Object], [Object], [Object], [Object]],
		studentGroup: 'SG20221205092007_4034',
		hasInfo: false,
		code: 0,
		cellState: 'STANDARD',
		priority: 5,
		is: { standard: true, event: false },
		roomCapacity: 0,
		studentCount: 0,
	},
	{
		id: 22258518,
		lessonId: 275444,
		lessonNumber: 403400,
		lessonCode: 'LESSON',
		lessonText: '+Devices(hardware)',
		periodText: '',
		hasPeriodText: false,
		periodInfo: '',
		periodAttachments: [],
		substText: '',
		date: 20230331,
		startTime: 1130,
		endTime: 1200,
		elements: [[Object], [Object], [Object], [Object], [Object]],
		studentGroup: 'SG20221205092007_4034',
		hasInfo: false,
		code: 0,
		cellState: 'STANDARD',
		priority: 5,
		is: { standard: true, event: false },
		roomCapacity: 0,
		studentCount: 0,
	},
];
const f = [];
const cDates = [];
// const t = test.sort(function (a, b) {
// 	if (a.startTime !== b.startTime) return a.startTime - b.startTime;
// });
// t.forEach((el) => {
// 	if (!cDates.includes(el.date)) cDates.push(el.date);
// });
// console.log(cDates);
// // const g = t.sort(function (a, b) {
// // 	i++;
// // 	if (a.date !== b.date && !f.includes(a.date) && !f.includes(b.date)) {
// // 		if (a.date > b.date) f.push(b.date);
// // 		else f.push(a.date);
// // 		return '';
// // 	} else if (f.filter((obj) => obj.date === a.date).length < 2) {
// // 		f.push(a);
// // 	} else console.log('wat');
// // 	return;
// // });

// const w = [];
// cDates.forEach((date) => {
// 	const g = t.filter((obj) => obj.date === date);
// 	console.log(g[g.length - 1]);
// 	console.log(g[0]);
// });

const kaas = [
	{
		time: 140,
		date: 20230327,
	},
	{
		time: 090,
		date: 20230327,
	},

	{
		time: 150,
		date: 20230327,
	},
	{
		time: 090,
		date: 20230328,
	},
	{
		time: 140,
		date: 20230328,
	},
	{
		time: 150,
		date: 20230328,
	},
];

const kaasDates = [];

const check = [
	{
		time: 100,
		date: 100,
	},
	{
		time: 100,
		date: 100,
	},
	{
		time: 100,
		date: 200,
	},
	{
		time: 100,
		date: 200,
	},
];
console.log('-=-');
console.log(check[0].time === 111);
console.log(check[0].date === 111);
console.log('-=-');
const kaasChecked = [];

kaas.forEach((el) => {
	if (!kaasDates.includes(el.date)) kaasDates.push(el.date);
	else return;
});
console.log(kaasDates);
const wil = kaasDates.forEach((el) => {
	let i = 0;
	console.log(`el: ${el}`);
	const p = kaas.sort(function (a, b) {
		console.log(`${a.date} - ${b.date} - ${el}`);
		if (a.date === b.date && el === a.date) {
			if (kaasChecked.filter((obj) => obj.date === el).length < 2) {
				// if (a.time !== b.time) return a.time - b.time;
				if (
					a.time !== b.time &&
					kaasChecked.filter((obj) => obj.date === el).length < 2
				) {
					if (
						!kaasChecked[i].match(a.time) &&
						kaasChecked[i]?.time !== b.time
					) {
						if (a.time < b.time)
							kaasChecked.push({ date: a.date, time: a.time });
						else kaasChecked.push({ date: b.date, time: b.time });
					}
				}
			} else console.log('what');
		}
	});
	i++;
	console.log('----');
});
console.log('----');
console.log('----');
console.log('----');
console.log(kaasChecked);
// console.log(kaas.filter((obj) => obj.date === 20230327));
